version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=12345
      - DB_NAME=parcial_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: parcial_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d parcial_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
